name: Test, build, release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**/release.yaml'
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    uses: lukaszraczylo/shared-actions/.github/workflows/go-release-cgo.yaml@main
    with:
      go-version: "1.25"
      rolling-release-tag: "v1"
      platforms: >-
        [
          {"os":"macos-15-intel","goos":"darwin","goarch":"amd64","platform":"darwin_amd64"},
          {"os":"macos-latest","goos":"darwin","goarch":"arm64","platform":"darwin_arm64"},
          {"os":"ubuntu-latest","goos":"linux","goarch":"amd64","platform":"linux_amd64"},
          {"os":"ubuntu-24.04-arm","goos":"linux","goarch":"arm64","platform":"linux_arm64"},
          {"os":"windows-latest","goos":"windows","goarch":"amd64","platform":"windows_amd64"}
        ]
    secrets: inherit
